In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r"data-disease-symptom-description/dataset.csv")
data.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches       NaN       NaN       NaN       NaN       NaN   
1                   NaN       NaN       NaN       NaN       NaN       NaN   
2                   NaN       NaN       NaN       NaN       NaN       NaN   
3                   NaN       NaN       NaN       NaN       NaN       NaN   
4                   NaN       NaN       NaN       NaN       NaN       NaN   

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0        NaN        NaN        NaN        NaN        NaN        NaN   
1        NaN        NaN        NaN        NaN        NaN        NaN   
2        NaN        NaN        NaN        NaN        NaN        NaN   
3        NaN        NaN        NaN        NaN        NaN        NaN   
4        NaN        NaN        NaN        NaN        NaN        NaN   

  Symptom_16 Symptom_17  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [3]:
data.shape

(4920, 18)

In [4]:
data.columns

Index(['Disease', 'Symptom_1', 'Symptom_2', 'Symptom_3', 'Symptom_4',
       'Symptom_5', 'Symptom_6', 'Symptom_7', 'Symptom_8', 'Symptom_9',
       'Symptom_10', 'Symptom_11', 'Symptom_12', 'Symptom_13', 'Symptom_14',
       'Symptom_15', 'Symptom_16', 'Symptom_17'],
      dtype='object')

In [7]:
disease_list= data["Disease"].unique()

In [11]:
sorted_disease_list=sorted(disease_list)
print(sorted_disease_list)

['(vertigo) Paroymsal  Positional Vertigo', 'AIDS', 'Acne', 'Alcoholic hepatitis', 'Allergy', 'Arthritis', 'Bronchial Asthma', 'Cervical spondylosis', 'Chicken pox', 'Chronic cholestasis', 'Common Cold', 'Dengue', 'Diabetes ', 'Dimorphic hemmorhoids(piles)', 'Drug Reaction', 'Fungal infection', 'GERD', 'Gastroenteritis', 'Heart attack', 'Hepatitis B', 'Hepatitis C', 'Hepatitis D', 'Hepatitis E', 'Hypertension ', 'Hyperthyroidism', 'Hypoglycemia', 'Hypothyroidism', 'Impetigo', 'Jaundice', 'Malaria', 'Migraine', 'Osteoarthristis', 'Paralysis (brain hemorrhage)', 'Peptic ulcer diseae', 'Pneumonia', 'Psoriasis', 'Tuberculosis', 'Typhoid', 'Urinary tract infection', 'Varicose veins', 'hepatitis A']


In [15]:
c=0;
for i in sorted_disease_list:
    print("{} {}".format(c,i))
    c=c+1

0 (vertigo) Paroymsal  Positional Vertigo
1 AIDS
2 Acne
3 Alcoholic hepatitis
4 Allergy
5 Arthritis
6 Bronchial Asthma
7 Cervical spondylosis
8 Chicken pox
9 Chronic cholestasis
10 Common Cold
11 Dengue
12 Diabetes 
13 Dimorphic hemmorhoids(piles)
14 Drug Reaction
15 Fungal infection
16 GERD
17 Gastroenteritis
18 Heart attack
19 Hepatitis B
20 Hepatitis C
21 Hepatitis D
22 Hepatitis E
23 Hypertension 
24 Hyperthyroidism
25 Hypoglycemia
26 Hypothyroidism
27 Impetigo
28 Jaundice
29 Malaria
30 Migraine
31 Osteoarthristis
32 Paralysis (brain hemorrhage)
33 Peptic ulcer diseae
34 Pneumonia
35 Psoriasis
36 Tuberculosis
37 Typhoid
38 Urinary tract infection
39 Varicose veins
40 hepatitis A


In [16]:
data["Disease"].nunique()

41

In [17]:
column_list=list(data.columns)
column_list

['Disease',
 'Symptom_1',
 'Symptom_2',
 'Symptom_3',
 'Symptom_4',
 'Symptom_5',
 'Symptom_6',
 'Symptom_7',
 'Symptom_8',
 'Symptom_9',
 'Symptom_10',
 'Symptom_11',
 'Symptom_12',
 'Symptom_13',
 'Symptom_14',
 'Symptom_15',
 'Symptom_16',
 'Symptom_17']

In [18]:
for i in column_list:
    count_nan=data[i].isna().sum()
    print('{} -----  {}' .format(i,count_nan))

Disease -----  0
Symptom_1 -----  0
Symptom_2 -----  0
Symptom_3 -----  0
Symptom_4 -----  348
Symptom_5 -----  1206
Symptom_6 -----  1986
Symptom_7 -----  2652
Symptom_8 -----  2976
Symptom_9 -----  3228
Symptom_10 -----  3408
Symptom_11 -----  3726
Symptom_12 -----  4176
Symptom_13 -----  4416
Symptom_14 -----  4614
Symptom_15 -----  4680
Symptom_16 -----  4728
Symptom_17 -----  4848


In [19]:
column_list.remove('Disease');

In [20]:
for i in column_list:
    data[i].fillna("", inplace=True)

In [21]:
data.head()

Disease   Symptom_1              Symptom_2              Symptom_3  \
0  Fungal infection     itching              skin_rash   nodal_skin_eruptions   
1  Fungal infection   skin_rash   nodal_skin_eruptions    dischromic _patches   
2  Fungal infection     itching   nodal_skin_eruptions    dischromic _patches   
3  Fungal infection     itching              skin_rash    dischromic _patches   
4  Fungal infection     itching              skin_rash   nodal_skin_eruptions   

              Symptom_4 Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9  \
0   dischromic _patches                                                     
1                                                                           
2                                                                           
3                                                                           
4                                                                           

  Symptom_10 Symptom_11 Symptom_12 Symptom_13 Symptom_14 Symptom_15  \
0                                                                     
1                                                                     
2                                                                     
3                                                                     
4                                                                     

  Symptom_16 Symptom_17  
0                        
1                        
2                        
3                        
4

In [22]:
column_list.remove('Symptom_1')
for i in column_list:
    data["Symptom_1"]+=data[i]

In [23]:
data.head()


Disease                                          Symptom_1  \
0  Fungal infection  itching skin_rash nodal_skin_eruptions dischro...   
1  Fungal infection   skin_rash nodal_skin_eruptions dischromic _pa...   
2  Fungal infection   itching nodal_skin_eruptions dischromic _patches   
3  Fungal infection              itching skin_rash dischromic _patches   
4  Fungal infection             itching skin_rash nodal_skin_eruptions   

               Symptom_2              Symptom_3             Symptom_4  \
0              skin_rash   nodal_skin_eruptions   dischromic _patches   
1   nodal_skin_eruptions    dischromic _patches                         
2   nodal_skin_eruptions    dischromic _patches                         
3              skin_rash    dischromic _patches                         
4              skin_rash   nodal_skin_eruptions                         

  Symptom_5 Symptom_6 Symptom_7 Symptom_8 Symptom_9 Symptom_10 Symptom_11  \
0                                                                           
1                                                                           
2                                                                           
3                                                                           
4                                                                           

  Symptom_12 Symptom_13 Symptom_14 Symptom_15 Symptom_16 Symptom_17  
0                                                                    
1                                                                    
2                                                                    
3                                                                    
4

In [24]:
data.drop(data.columns[[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]], axis = 1, inplace = True)

In [25]:
data.shape

(4920, 2)

In [26]:
data.head(20)

Disease                                          Symptom_1
0   Fungal infection  itching skin_rash nodal_skin_eruptions dischro...
1   Fungal infection   skin_rash nodal_skin_eruptions dischromic _pa...
2   Fungal infection   itching nodal_skin_eruptions dischromic _patches
3   Fungal infection              itching skin_rash dischromic _patches
4   Fungal infection             itching skin_rash nodal_skin_eruptions
5   Fungal infection   skin_rash nodal_skin_eruptions dischromic _pa...
6   Fungal infection   itching nodal_skin_eruptions dischromic _patches
7   Fungal infection              itching skin_rash dischromic _patches
8   Fungal infection             itching skin_rash nodal_skin_eruptions
9   Fungal infection  itching skin_rash nodal_skin_eruptions dischro...
10           Allergy   continuous_sneezing shivering chills watering...
11           Allergy                shivering chills watering_from_eyes
12           Allergy      continuous_sneezing chills watering_from_eyes
13           Allergy   continuous_sneezing shivering watering_from_eyes
14           Allergy               continuous_sneezing shivering chills
15           Allergy                shivering chills watering_from_eyes
16           Allergy      continuous_sneezing chills watering_from_eyes
17           Allergy   continuous_sneezing shivering watering_from_eyes
18           Allergy               continuous_sneezing shivering chills
19           Allergy   continuous_sneezing shivering chills watering...

In [ ]:
'''
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
ps=PorterStemmer()
corpus=[]
'''

In [ ]:
'''
for i in range(0, len(data)):
    review=re.sub('[^a-zA-z]',' ',data['Symptom_1'][i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word) for word in review if not word in stopwords.words('english')]
    review=' '.join(review)
    corpus.append(review)
'''

In [28]:
import re
corpus=[]
for i in range(0,len(data)):
    review=re.sub('[^a-zA-z]',' ',data['Symptom_1'][i])
    review=review.lower()
    review=review.split()
    review=' '.join(review)
    corpus.append(review)

In [29]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=5000)
x=cv.fit_transform(corpus).toarray()

In [30]:
import pickle
pickle.dump(cv, open('cv-transform.pkl', 'wb'))

In [31]:
x.shape

(4920, 135)

In [32]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
data["Disease"]=encoder.fit_transform(data["Disease"])

In [33]:
data.head(20)

Disease                                          Symptom_1
0        15  itching skin_rash nodal_skin_eruptions dischro...
1        15   skin_rash nodal_skin_eruptions dischromic _pa...
2        15   itching nodal_skin_eruptions dischromic _patches
3        15              itching skin_rash dischromic _patches
4        15             itching skin_rash nodal_skin_eruptions
5        15   skin_rash nodal_skin_eruptions dischromic _pa...
6        15   itching nodal_skin_eruptions dischromic _patches
7        15              itching skin_rash dischromic _patches
8        15             itching skin_rash nodal_skin_eruptions
9        15  itching skin_rash nodal_skin_eruptions dischro...
10        4   continuous_sneezing shivering chills watering...
11        4                shivering chills watering_from_eyes
12        4      continuous_sneezing chills watering_from_eyes
13        4   continuous_sneezing shivering watering_from_eyes
14        4               continuous_sneezing shivering chills
15        4                shivering chills watering_from_eyes
16        4      continuous_sneezing chills watering_from_eyes
17        4   continuous_sneezing shivering watering_from_eyes
18        4               continuous_sneezing shivering chills
19        4   continuous_sneezing shivering chills watering...

In [34]:
data["Disease"].value_counts()

39    120
33    120
25    120
21    120
17    120
13    120
9     120
5     120
1     120
40    120
36    120
32    120
28    120
24    120
20    120
16    120
12    120
8     120
4     120
29    120
37    120
35    120
2     120
31    120
27    120
23    120
19    120
15    120
11    120
7     120
3     120
38    120
34    120
30    120
26    120
22    120
18    120
14    120
10    120
6     120
0     120
Name: Disease, dtype: int64

In [35]:
y=data["Disease"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=100)

In [36]:
from sklearn.naive_bayes import MultinomialNB
classifier=MultinomialNB().fit(X_train,y_train)

In [37]:
pickle.dump(classifier, open('model.pkl', 'wb'))

In [ ]:
#from sklearn.model_selection import cross_val_score
#score=cross_val_score(classifier,x,y,cv=10)

In [38]:
y_pred=classifier.predict(X_test)

In [41]:
from sklearn.metrics import confusion_matrix, accuracy_score,recall
confusion_m=confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)

print(accuracy)


ImportError: cannot import name 'recall' from 'sklearn.metrics' (C:\Users\Asus\Anaconda3\lib\site-packages\sklearn\metrics\__init__.py)

In [40]:
print(confusion_m)


[[36  0  0 ...  0  0  0]
 [ 0 28  0 ...  0  0  0]
 [ 0  0 40 ...  0  0  0]
 ...
 [ 0  0  0 ... 33  0  0]
 [ 0  0  0 ...  0 34  0]
 [ 0  0  0 ...  0  0 35]]


In [ ]:
print(y_test)

In [ ]:
print(y_pred)

In [ ]:
print(data["Disease"])
